SUPABASE_URL = "https://lczakwhqgpwgurbethyl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjemFrd2hxZ3B3Z3VyYmV0aHlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2Mzc3NjIsImV4cCI6MjA2NTIxMzc2Mn0.hJeo-U_gCC8HCCb_E9-rFpdl0pIXz3DAJJEaIExl6w4"
